MODEL:
  MASK_ON: True
  META_ARCHITECTURE: "OneStageDetector"
  BACKBONE:
    NAME: "build_fcos_mvn2_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "MEInst"
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [256, 256, 256]
DATASETS:
  TRAIN: ("custom_coco_train",)
  TEST: ("custom_coco_train",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TRAIN: (320,)
  MAX_SIZE_TEST: 320
  MIN_SIZE_TEST: 320
VERSION: 2
